### PR TITLE
Store logs from failed CI as artifacts

### LINKED ISSUE #507: Store logs from failed CI as artifacts
Integration tests store logs in disk, but we cannot access them as a user of Github actions. Without logs, it's very hard to debug. 

We can upload logs as Github actions artifacts.

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Closes #507

If CI fails, integration test artifacts (logs, etc...) are uploaded to Github Actions. 

The uploaded artifacts can be found at the bottom of the `Summary` page of each action.
image

Currently, we upload artifacts without compressing them (since it's simpler and doesn't cost), but they're automatically compressed as a zip when you download them.

### CODE REVIEW

File: tests/src/nodes/nomos.rs [hunk 1]
```diff
@@ -58,7 +58,13 @@ impl NomosNode {
...
         // Waku stores the messages in a db file in the current dir, we need a different
         // directory for each node to avoid conflicts
-        let dir = tempfile::tempdir().unwrap();
+        //
+        // NOTE: We could create dirs inside of the OS-default tempdir location.
+        // But, in Windows hosted by Github Actions, it's easier to use the current location
+        // in terms of uploading artifacts to Github,
+        // because source code and system dirs are located on different disks.
+        let dir = tempfile::TempDir::new_in(std::env::current_dir().unwrap()).unwrap();
+
```
Comment (youngjoon-lee) [inline tests/src/nodes/nomos.rs:67]: On Windows hosted by Github Actions,
```
persisting directory C:\Users\RUNNER~1\AppData\Local\Temp\.tmp5A9Xxs -> D:\a\nomos-node\nomos-node\tests\.tmp5A9Xxs
called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: CrossesDevices, message: "The system cannot move the file to a different disk drive." }
```

Comment (bacv) [reply tests/src/nodes/nomos.rs:67]: This happened before and the PR resolves it, right?

**Review by bacv — APPROVED** [review]

File: tests/src/nodes/nomos.rs (hunk 1 above)
Comment (youngjoon-lee) [reply tests/src/nodes/nomos.rs:67]: This has never happened before, because we haven't tried to upload artifacts to Github so far ;)

At the begining when I try to implement this PR, I implemented like below:
```rust
let dir = tempfile::tempdir().unwrap();   // using the OS-default
...

fn drop() {
  ...

  // for example,
  std::fs::rename(dir, "$CWD/blahblah"); 
}
```
so that Github actions can upload the artifact `$CWD/blahblah` (also because it's hard to pass the tempdir path in the OS-default location to the Github actions).

But, the `std::fs::rename` failed with the error above: `The system cannot move the file to a different disk drive.`, in Windows. Of course, I could use `copy` instead of `rename`. But, I chose to create a tempdir under the CWD instead of OS-default location.

Comment (youngjoon-lee) [reply tests/src/nodes/nomos.rs:67]: I'll refine the comment in the source code. Thank you!

Comment (youngjoon-lee) [reply tests/src/nodes/nomos.rs]: Refined comment: 84965d8b

**Review by zeegomo — APPROVED** [review]
