### PR TITLE
fix(blend): correctly check the last layer in `MockBlendMessage`

### LINKED ISSUE #956: Fix `MockBlendMessage::unwrap` to correctly check if the current layer is the last
In the current `MockBlendMessage`, we determine that the current layer is the last if the next node ID is `[0u8; 32]`. However, users can use `[0u8; 32]` as an actual node ID. If users use the `[0u8; 32]` as the 2nd node ID, then the implementation determines that the 1st layer is the last. This is a bug.

`MockBlendMessage` is used in simulations.

### PR DESCRIPTION
**Pull request by youngjoon-lee**
## 1. What does this PR implement?

Closes #956

As explained in #956, this PR fixes `MockBlendMessage` to correctly check if the current layer is the last. Previously, it has been used `[0u8; 32]` to represent a dummy node ID, but it is common that users use the `[0u8; 32]` as an actual node ID. Then, the check logic fails. So, this PR uses `[u8::MAX; 32]` as a dummy node ID, and return error if users use it as an actual node ID. I think this fix is good enough because it's just a mock (used in simulations).

## 2. Does the code have enough context to be clearly understood?

Yes

## 3. Who are the specification authors and who is accountable for this PR?

@youngjoon-lee 

## 4. Is the specification accurate and complete?

Yes

## 5. Does the implementation introduce changes in the specification?

No

## Checklist

> [!WARNING]  
> Do not merge the PR if any of the following is missing:

* [ ] 1. Description added.
* [ ] 2. Context and links to Specification document(s) added.
* [ ] 3. Main contact(s) (developers and specification authors) added
* [ ] 4. Implementation and Specification are 100% in sync including changes. This is critical.
* [ ] 5. Link PR to a specific milestone.

### CODE REVIEW

File: nomos-blend/message/src/mock/error.rs [hunk 1]
```diff
@@ -1,11 +1,13 @@
...
+#[derive(thiserror::Error, Debug, PartialEq)]
 pub enum Error {
     #[error("Invalid blend message format")]
     InvalidBlendMessage,
     #[error("Payload is too large")]
     PayloadTooLarge,
     #[error("Invalid number of layers")]
     InvalidNumberOfLayers,
+    #[error("Invalid public key")]
+    InvalidPublicKey,
```
Comment (youngjoon-lee) [inline nomos-blend/message/src/mock/error.rs:10]: Instead of `InvalidNodeId`, I use this name because the trait `BlendMessage` uses the name `PublicKey` (not `NodeId`). In the `MockBlendMessage`, a node ID is used as a public key, but I think the error should use the generic term: public key.

**Comment by danielSanchezQ** [comment]
wdym it is common that users use `[0u8; 32]` as NodeId? I think it is actually the same case as `u8::MAX`.

**Comment by youngjoon-lee** [comment]
> wdym it is common that users use `[0u8; 32]` as NodeId? I think it is actually the same case as `u8::MAX`.

The simulation code generates node IDs from 0 to N. We can avoid this bug by generating node IDs from 1 or larger, but I wanted to say that people will tend to generate node IDs from 0 when they use this mock message implementation.
So, I used u8::MAX for the dummy. Of course, users can use u8::MAX but then this mock returns an error. I think this is more natural.

**Comment by danielSanchezQ** [comment]
> > wdym it is common that users use `[0u8; 32]` as NodeId? I think it is actually the same case as `u8::MAX`.
> 
> The simulation code generates node IDs from 0 to N. We can avoid this bug by generating node IDs from 1 or larger, but I wanted to say that people will tend to generate node IDs from 0 when they use this mock message implementation. So, I used u8::MAX for the dummy. Of course, users can use u8::MAX but then this mock returns an error. I think this is more natural.

Ah that makes sense now. I would say it really is our fault as we could use random ids in the sims, but using integers is handier for debugging though. 
I understand it now. Thanks.

**Review by danielSanchezQ — APPROVED** [review]
