### PR TITLE
fix(blend): complete STP before terminating core service

### LINKED ISSUE #1855: Core service terminates by itself before transition is done
Even though `instance.rs` maintains the previous `CoreMode` (as a form of `EdgeAfterCore` and `BroadcastAfterCore`), the core service is not maintained during the session transition period in the current codebase. The core service terminates by itself as soon as it receives a new session where it is not core anymore.

This is a bug. The core service shouldn’t be terminated until the last session transition is done. 

~~In the current codebase, this kind of bugs can be produced easily because `instance.rs` cannot check whether a certain service is running or was terminated.~~

~~There may be various ways to resolve this issue, but I think the main point is having transition logic in one place and not producing scenarios where services are terminated (panicked) silently.~~

~~I think the best approach would be redesigned the core and edge module without using Overwatch. Since they are currently Overwatch services, it is limited to manage their lifecycle and transition. We could design a nice state transition model, instead. I am preparing a PoC. I think it is time to try this redesigning, rather than making the core service more complicated.~~

~~In short, I am thinking about having three states: Core, Edge, and Broadcast. A node transitions its state only when its role is changed in a new session.
There is one special case: Transitioning from core. Before switching to the other state, we can spawn-and-forget a task which handles and finishes the last session transition period. We don’t need to define a dedicated state for the task because we don’t need to interact with it. 
This design can be also implemented with keeping the Overwatch services model, but I think it’s easier without Overwatch.~~

UPDATE:
We can fix this in a simple way. I will modify the core service to continue processing the previous session until the next STPExpired event is arrived. We can simply exit from the main event loop once we receive a new session where the node is not core anymore, and start another event loop only for processing the last session transition during only STP. After that, core service must terminate by itself.
This issue is also related to https://github.com/logos-co/nomos/issues/1860, but not directly. So, this can be resolved separately.

### PR DESCRIPTION
**Pull request by youngjoon-lee**
## 1. What does this PR implement?
Closes #1855 

**Background:**
Previously, the core service has been terminating by itself once it receives a new session where it's not core anymore. That's wrong because the core service should also complete the last STP (session transition period) before shutdown. 

**Solution:**
In this PR, the core service still exits from the main event loop once it receives a non-core session. But, instead of terminating immediately, it runs another event loop only for the last STP. This event loop does less jobs than the main loop. Also, this stops once a STP has passed. Then, the core service finally terminates.

The test is coming as a next PR. Since the core service structure is not good for testing, I did some refactoring.

NOTE: This PR doesn't fix https://github.com/logos-co/nomos/issues/1860 (service lifecycle mgmt in proxy service). I will work on it separately.

## 2. Does the code have enough context to be clearly understood?

yes

## 3. Who are the specification authors and who is accountable for this PR?

@youngjoon-lee @ntn-x2 @madxor 

## 4. Is the specification accurate and complete?

yes

## 5. Does the implementation introduce changes in the specification?

no

## Checklist

> [!WARNING]  
> Do not merge the PR if any of the following is missing:

* [x] 1. The PR title follows the Conventional Commits [specification](https://www.notion.so/How-to-open-a-Pull-Request-215261aa09df80deb538ed59f5e4e0b5).
* [x] 2. Description added.
* [x] 3. Context and links to Specification document(s) added.
* [x] 4. Main contact(s) (developers and specification authors) added
* [x] 5. Implementation and Specification are 100% in sync including changes. This is critical.
* [x] 6. Link PR to a specific milestone.

### CODE REVIEW

File: nomos-services/blend/src/core/mod.rs [hunk 1]
```diff
@@ -514,23 +514,60 @@ where
...
+        // session transition period.
+        //
+        // First, drop unnecessary streams to not block senders.
+        drop((
+            // Don't receive local data messages, as they shouldn't be sent in the old session.
+            inbound_relay,
+            // Don't receive secret PoL info updates, as new messages are not generated for the old
+            // session.
+            secret_pol_info_stream,
+        ));
```
Comment (youngjoon-lee) [inline nomos-services/blend/src/core/mod.rs:550]: I'd thought about this point multiple time, but ended up having two loops in the same place and having this `drop` explicitly between the loops.

I considered defining a function for each loop and removing the `drop` by making the 1st function consumes those resources, but I realized that it could cause potential misuse, and not good for readability. I want the the 2nd loop always comes after the 1st one.

File: nomos-services/blend/src/core/mod.rs [hunk 2]
```diff
@@ -514,23 +514,60 @@ where
...
+        loop {
+            tokio::select! {
+                Some(incoming_message) = blend_messages.next() => {
+                    current_recovery_checkpoint = handle_incoming_blend_message(incoming_message, &mut message_scheduler, &crypto_processor, &mut blending_token_collector, current_recovery_checkpoint);
+                }
+                Some(round_info) = message_scheduler.next() => {
+                    current_recovery_checkpoint = handle_release_round(round_info, &mut crypto_processor, &mut rng, &backend, &network_adapter, current_recovery_checkpoint).await;
```
Comment (ntn-x2) [inline nomos-services/blend/src/core/mod.rs:557]: I think we don't want to deal with release rounds anymore either, no? We only accept incoming messages, but should not be pushing any new messages out.

**Review by ntn-x2 — APPROVED** [review]
Looks good! Just left a comment about probably one more stream we should drop.

File: nomos-services/blend/src/core/mod.rs (hunk 2 above)
Comment (youngjoon-lee) [reply nomos-services/blend/src/core/mod.rs:557]: I think we still need the scheduler because we need to forward (or broadcast) any processed messages received during STP in the line 554. Please correct me if I'm missing anything.

Comment (youngjoon-lee) [reply nomos-services/blend/src/core/mod.rs:557]: Hm. I think I know what you mean. We may not need to generate new cover messages during STP when its core role is fading out. I will open a discussion in Discord since it's not defined in the spec. If necessary, we should probably refactor the `message_scheduler` or introduce any better way.

I think it's okay to merge this PR for now because generating new cover messages here doesn't make any issue, I think. I will add more tests soon when fixing additional bugs. I anyway have to write tests to cover all the cases/behaviors of session transitions.

Comment (youngjoon-lee) [reply nomos-services/blend/src/core/mod.rs:557]: As discussed in https://discord.com/channels/1111286067413405788/1434779184206712862, we keep the current implementation that generates new cover messages during the last STP because it doesn't break the definition of STP, but beneficial in terms of privacy.
